version: '3'

services:
  dwh:
    container_name: dwh
    image: postgres:11-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - database.env
    ports:
      - 5432:5432

  etl:
    container_name: etl_service
    volumes:
      - ./data/events/inbox/cards:/app/events/cards
      - ./data/events/inbox/users:/app/events/users
    depends_on:
      - dwh
      - zookeeper
      - kafka
    command: ["./app/wait-for-it.sh", "kafka:9092", "--", "java","-jar","/app/app.jar"]
    image: data-eng-challenge/etl:latest
    build: 
      context: ./etl
    ports:
      - 8080:8080
      - 8081:8081

  users:
    container_name: users_service
    volumes:
      - ./data/events/inbox/users:/app/events
      - ./data/logs/users:/app/logs
    depends_on:
      - dwh
    image: data-eng-challenge/users:latest
    build: 
      context: ./users
      dockerfile: ../Dockerfile

  cards:
    container_name: cards_service
    volumes:
      - ./data/events/inbox/cards:/app/events
      - ./data/logs/cards:/app/logs
    depends_on:
      - dwh
    image: data-eng-challenge/cards:latest
    build: 
      context: ./cards
      dockerfile: ../Dockerfile

volumes:
  db_data:
